/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.hyunseda.market.presentation;

import co.com.hyunseda.market.service.IProductService;
import co.com.hyunseda.market.service.Product;


import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.lang.Long;
import javax.swing.JOptionPane;

/**
 *
 * @author Libardo Pantoja, Julio A. Hurtado
 */
public class GUIProductsFind extends javax.swing.JDialog {
    private IProductService productService;
    /**
     * Creates new form GUIProductsFind
     */
    public GUIProductsFind(java.awt.Frame parent, boolean modal,IProductService productService) {
        super(parent, modal);
        initComponents();
        initializeTable();
        this.productService = productService;
        setLocationRelativeTo(null); //centrar al ventana
    }

    private void initializeTable() {
        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Id", "Name", "Description"
                }
        ));
    }
    
        private void fillTable(List<Product> listProducts) {
        initializeTable();
        DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();

        Object rowData[] = new Object[3];//No columnas
        for (int i = 0; i < listProducts.size(); i++) {
            rowData[0] = listProducts.get(i).getProductId();
            rowData[1] = listProducts.get(i).getName();
            rowData[2] = listProducts.get(i).getDescription();
            
            model.addRow(rowData);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        pnlNorth = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rdoId = new javax.swing.JRadioButton();
        rdoName = new javax.swing.JRadioButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnSearchAll = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Búsqueda de productos");

        pnlCenter.setLayout(new java.awt.BorderLayout());

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProducts);

        pnlCenter.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlCenter, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Buscar por:");
        pnlNorth.add(jLabel1);

        buttonGroup1.add(rdoId);
        rdoId.setSelected(true);
        rdoId.setText("Id");
        rdoId.setName(""); // NOI18N
        rdoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoIdActionPerformed(evt);
            }
        });
        pnlNorth.add(rdoId);

        buttonGroup1.add(rdoName);
        rdoName.setText("Nombre del producto");
        rdoName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNameActionPerformed(evt);
            }
        });
        pnlNorth.add(rdoName);

        txtSearch.setPreferredSize(new java.awt.Dimension(62, 32));
        pnlNorth.add(txtSearch);

        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        pnlNorth.add(btnSearch);

        btnSearchAll.setText("Buscar Todos");
        btnSearchAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAllActionPerformed(evt);
            }
        });
        pnlNorth.add(btnSearchAll);

        getContentPane().add(pnlNorth, java.awt.BorderLayout.PAGE_START);

        btnClose.setText("Cerrar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSearchAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAllActionPerformed
        fillTable(productService.findAllProducts());
    }//GEN-LAST:event_btnSearchAllActionPerformed

    private void rdoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoIdActionPerformed
                                                                  
    // Habilitar la casilla de búsqueda por ID si está seleccionada
    if (rdoId.isSelected()) {
        txtSearch.setEnabled(true);
        txtSearch.setText(""); // Limpiar el texto de búsqueda
        txtSearch.requestFocus(); // Colocar el foco en la casilla de búsqueda
    } else {
        // Deshabilitar la casilla de búsqueda por ID si no está seleccionada
        txtSearch.setEnabled(false);
        txtSearch.setText(""); // Limpiar el texto de búsqueda
    }

    }//GEN-LAST:event_rdoIdActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
                                 
    // Verificar si se seleccionó la búsqueda por ID
    if (rdoId.isSelected()) {
        // Obtener el texto ingresado por el usuario en la casilla de búsqueda
        String searchText = txtSearch.getText().trim();
        
        // Verificar si el campo de búsqueda no está vacío
        if (!searchText.isEmpty()) {
            try {
                // Convertir el texto a un Long (ID)
                Long productId = Long.parseLong(searchText);
                
                // Realizar la búsqueda por ID
                Product foundProduct = productService.findProductById(productId);
                
                // Verificar si se encontró el producto
                if (foundProduct != null) {
                    // Limpiar la tabla y agregar el producto encontrado
                    DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();
                    model.setRowCount(0); // Limpiar la tabla
                    model.addRow(new Object[]{foundProduct.getProductId(), foundProduct.getName(), foundProduct.getDescription()});
                } else {
                    // Mostrar un mensaje indicando que no se encontró el producto
                    JOptionPane.showMessageDialog(this, "No se encontró ningún producto con el ID especificado.", "Producto no encontrado", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (NumberFormatException e) {
                // Mostrar un mensaje de error si el texto ingresado no es un número válido
                JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID válido.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Mostrar un mensaje indicando que el campo de búsqueda está vacío
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID para buscar.", "Campo vacío", JOptionPane.INFORMATION_MESSAGE);
        }
    } else if (rdoName.isSelected()) {
        String searchText=txtSearch.getText().trim();
        if(!searchText.isEmpty()){
            try{
                Product foundProduct = productService.findProductByName(searchText);
                
                if(foundProduct!=null){
                   DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();
                    model.setRowCount(0); // Limpiar la tabla
                    model.addRow(new Object[]{foundProduct.getProductId(), foundProduct.getName(), foundProduct.getDescription()}); 
                }
                else {
                    // Mostrar un mensaje indicando que no se encontró el producto
                    JOptionPane.showMessageDialog(this, "No se encontró ningún producto con el nombre especificado.", "Producto no encontrado", JOptionPane.INFORMATION_MESSAGE);
                }
            }catch (NumberFormatException e) {
                // Mostrar un mensaje de error si el texto ingresado no es un número válido
                JOptionPane.showMessageDialog(this, "Por favor, ingrese un nombre válido.","Error", JOptionPane.ERROR_MESSAGE);
            }

    } 
     
        else {
   
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un nombre para buscar .", "Campo vacio", JOptionPane.INFORMATION_MESSAGE);
    }
    }

    }//GEN-LAST:event_btnSearchActionPerformed

    private void rdoNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNameActionPerformed
        if (rdoName.isSelected()) {
        txtSearch.setEnabled(true);
        txtSearch.setText(""); // Limpiar el texto de búsqueda
        txtSearch.requestFocus(); // Colocar el foco en la casilla de búsqueda
    } else {
        // Deshabilitar la casilla de búsqueda por nombre si no está seleccionada
        txtSearch.setEnabled(false);
        txtSearch.setText(""); // Limpiar el texto de búsqueda
    }
    }//GEN-LAST:event_rdoNameActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchAll;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlNorth;
    private javax.swing.JRadioButton rdoId;
    private javax.swing.JRadioButton rdoName;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
